### PR TITLE
Feat: Add Groups, Iterator over capture_groups of match

### PR DESCRIPTION
**Pull request by RageKnify**
closes ridiculousfish/regress#7

- [x] docs
- [ ] tests

### CODE REVIEW

**Comment by RageKnify** [comment]
Do you see the need for tests or is the PR ok as is @ridiculousfish ?
I think I would also need a version bump and for you to publish it on crates.io so it can be used in `boa`.

**Comment by ridiculousfish** [comment]
Merged as c54cead30908ec7bbe88a89625d4219aaccc7a90. Thank you!!

**Comment by ridiculousfish** [comment]
Published as regress 0.1.4

**Comment by RageKnify** [comment]
Just an heads up @ridiculousfish , but I believe you should have also bumped the version in the `Cargo.toml` when you published it as `0.1.4`.

**Comment by ridiculousfish** [comment]
@RageKnify I believe I bumped the version in 25e8c6863de2052bbf6a08979accf0240fb897cc but I may have messed it up, is it OK?

**Comment by ridiculousfish** [comment]
Ahh I forgot to `git push`. Version was bumped in 25e8c6863de2052bbf6a08979accf0240fb897cc which is what was published to crates.io. Thank you, nice catch!

**Pull request closed without merging**
